//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaseEFEntities : DbContext
    {
        public BaseEFEntities()
            : base("name=BaseEFEntities")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Soma> Soma { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Telefones> Telefones { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
    }
}
