//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefones
    {
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public string Ddd { get; set; }
        public string Numero { get; set; }
        public Nullable<int> TipoId { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
